settings.cmake: Use OpenSBI instead of BBL
seL4/sel4test pull request #28
Opened 2020-10-23 22:31 UTC by alistair23

This is part of a collection of PRs to convert from using the legacy BBL and riscv-pk to OpenSBI.

Other PRs include:

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

2020-10-28 04:22 UTC, szhuang approved these changes

2020-12-16 13:55 UTC, axel-h requested changes

2020-12-18 17:55 UTC, alistair23 commented
I have updated this to address comments.

2020-12-19 15:14 UTC, axel-h approved these changes

2021-01-05 19:26 UTC, alistair23 commented
Ping!

2021-01-20 17:19 UTC, alistair23 commented
Ping!

2021-03-08 23:52 UTC, oliver-wm commented
@ssrg-bamboo `test`

2021-03-08 23:54 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2021-03-08 23:55 UTC, ssrg-bamboo commented
All the tests we ran have passed! Nice job!

2021-03-16 02:26 UTC, closed without merging

2021-03-16 13:51 UTC, alistair23 commented
It doesn't seem like this has been merged.

2021-03-16 21:49 UTC, lsf37 commented
Sorry, @oliver-wm should have commented while closing:

It's been merged internally and will be pushed out to on GitHub as soon as CI passes (there are some networking problems which makes that process slow at them moment, because it leads to intermittent hardware test failures)

We're working on getting rid of that internal merge step, and hopefully that will make things less painful soon.